/**
 * Generated by Eclipse Mita.
 * @date 2018-10-07 22:44:02
 */


#ifndef SENSORBUTTON_TWO_BUTTON_TWO_H
#define SENSORBUTTON_TWO_BUTTON_TWO_H

#include <BCDS_Retcode.h>


/**
 * Sets up the button_two.
 */
Retcode_T SensorButton_two_Setup(void);

/**
 * Enables the button_two sensor.
 */
Retcode_T SensorButton_two_Enable(void);
	


#endif

